# Generated by Django 2.1.3 on 2019-06-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('aboutus_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('picture', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ActsAndRegulation',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('document', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcements_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=500)),
                ('no_of_seats', models.IntegerField()),
                ('appli_start_date', models.DateField()),
                ('appli_end_date', models.DateField()),
                ('prgm_start_date', models.DateField()),
                ('prgm_end_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('program_fee', models.CharField(max_length=100)),
                ('batch_dis_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('credit', models.CharField(blank=True, max_length=100)),
                ('internal_mark', models.IntegerField()),
                ('external_mark', models.IntegerField()),
                ('total_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_programme_mapping',
            fields=[
                ('course_prg_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department_Name', models.CharField(blank=True, max_length=100)),
                ('Department_description', models.TextField(blank=True, max_length=3000)),
                ('meta_tag', models.CharField(blank=True, max_length=150)),
                ('Department_code', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='directorate',
            fields=[
                ('directorate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('fax', models.CharField(blank=True, max_length=70)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('logo', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('docFile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('picture', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='gallerytitle',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('highlights_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField()),
                ('thumbnail', models.CharField(blank=True, max_length=250)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.gallerytitle')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('notify_id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_title', models.CharField(max_length=1000)),
                ('notify_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('prgm_id', models.IntegerField()),
                ('applicant_no', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('trans_id', models.CharField(max_length=500)),
                ('trans_amount', models.IntegerField()),
                ('trans_date', models.DateTimeField()),
                ('res_code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEligibility',
            fields=[
                ('eligibility_id', models.AutoField(primary_key=True, serialize=False)),
                ('eligibility_question', models.CharField(blank=True, max_length=2000)),
                ('default_answer', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_code', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=20000)),
                ('programme_Struture', models.CharField(blank=True, max_length=1000)),
                ('syllabus', models.CharField(blank=True, max_length=1000)),
                ('brochure', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.CharField(blank=True, max_length=100)),
                ('meta_tag', models.CharField(blank=True, max_length=300)),
                ('eligibility', models.TextField(blank=True, max_length=20000)),
                ('program_type', models.CharField(blank=True, max_length=10)),
                ('no_of_semester', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('research_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('guide', models.CharField(max_length=100)),
                ('synopsis', models.TextField(max_length=1000)),
                ('research_documents', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplicants',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('applied_date', models.DateTimeField()),
                ('applicant_status', models.CharField(max_length=100)),
                ('course_fee', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=500)),
                ('applicant_id', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Batch')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='studycentre',
            fields=[
                ('studycentre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('managed_by', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='programeligibility',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Programme'),
        ),
        migrations.AddField(
            model_name='course_programme_mapping',
            name='prg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Programme'),
        ),
        migrations.AddField(
            model_name='batch',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.Programme'),
        ),
        migrations.AddField(
            model_name='batch',
            name='study_centre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_module.studycentre'),
        ),
    ]
