"""
Django settings for DASTP project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8%w%oi((iwcqxv2b97$@%+e72te1yht#vee$1if5mpgsajwp4-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'info_module',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DASTP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DASTP.wsgi.application'


#===============PAYMENT GATEWAY CONFIGURATIONS========================#

# Paytm Testing details
# PAYTM_MERCHANT_KEY = "gKpu7IKaLSbkchFS" 
# PAYTM_MERCHANT_ID = "rxazcv89315285244163"
# PAYTM_WEBSITE = 'WEBSTAGING'

# # MG university details
PAYTM_MERCHANT_KEY = "y8Pl2RuxzR4no5rB" 
PAYTM_MERCHANT_ID = "Mahata70791090225920"
PAYTM_WEBSITE = 'MahataWEB'

# CALLBACK_URL='http://192.168.1.54:8000/api/gateway/paymentresponse' # Local Dev Server
CALLBACK_URL='http://52.63.114.210:6100/api/gateway/paymentresponse' # AWS Dev Server
# CALLBACK_URL='http://54.66.133.32:6100/api/gateway/paymentresponse' # AWS QA Server
# CALLBACK_URL='http://13.127.50.187:6100/api/gateway/paymentresponse' # MG Prod Server

# REDIRECT_URL="http://192.168.1.129:4200/#/paymentresponse/"# Local Dev Server
REDIRECT_URL="http://52.63.114.210/#/paymentresponse/"# AWS Dev Server
# REDIRECT_URL="http://54.66.133.32:80/#/paymentresponse/"# AWS QA Server
# REDIRECT_URL="http://13.127.50.187:80/#/paymentresponse/"# MG Prod Sever

#===============PAYMENT GATEWAY CONFIGURATIONS========================#

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dastp_be_qa',
#         'HOST': 'dastp.cq9dav1ixlfr.ap-southeast-1.rds.amazonaws.com',
#         'PORT': '3306',
#         'USER': 'root',
#         'PASSWORD': 'root1234',
    
#     }
# }

# Development server
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dastp_be_dev',
#         'HOST': 'dastp.cq9dav1ixlfr.ap-southeast-1.rds.amazonaws.com',
#         'PORT': '3306',
#         'USER': 'root',
#         'PASSWORD': 'root1234',
    
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kem_dasp_be',
        'HOST': 'dastp.cq9dav1ixlfr.ap-southeast-1.rds.amazonaws.com',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'root1234',
    
    }
}

# Production server mg server
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dastp_be',
#         'HOST': 'mgu-online.cgtqmgscafyc.ap-south-1.rds.amazonaws.com',
#         'PORT': '3306',
#         'USER': 'mgonlinedb',
#         'PASSWORD': 'Mgudb1122',
    
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR,'static'),)
MEDIA_URL = '/media/'
MEDIA_ROOT=BASE_DIR
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST='192.168.0.196:3000'
